drop table BOWLS_CLUB.t_bowl_player;
drop table BOWLS_CLUB.t_api_permission;
drop table BOWLS_CLUB.t_bowl_competition;
drop table BOWLS_CLUB.t_bowl_game_player_performance;
drop table BOWLS_CLUB.t_user_info;
drop table BOWLS_CLUB.t_bowl_team;

create table t_bowl_competition
(
    id               bigint auto_increment
        primary key,
    team_id          bigint       default -1                                 not null comment 'team id ',
    competition_name varchar(128) default 'New Competition'                  not null comment 'Competition Name',
    competition_day  varchar(256) default 'Day of competition for each week' null
)
    comment 'record for a single bowl match';

INSERT INTO BOWLS_CLUB.t_bowl_competition (id, team_id, competition_name, competition_day) VALUES (4, 0, 'Weekend Pennant', 'Saturday');
INSERT INTO BOWLS_CLUB.t_bowl_competition (id, team_id, competition_name, competition_day) VALUES (31, 0, 'Midweek Pennant', 'Wednesday|Tuesday');
INSERT INTO BOWLS_CLUB.t_bowl_competition (id, team_id, competition_name, competition_day) VALUES (32, 0, 'Thursday 7-B-Side', 'Thursday|Friday');
INSERT INTO BOWLS_CLUB.t_bowl_competition (id, team_id, competition_name, competition_day) VALUES (68, 0, 'New Night Pennant', 'Wednesday');

create table t_bowl_game_player_performance
(
    id                int auto_increment
        primary key,
    player_id         bigint                  not null,
    competition_id    bigint                  not null,
    performance_score int          default -1 not null,
    season            varchar(256)            not null comment 'The Season of the competition(seperate by year)',
    match_time        datetime                not null,
    position          varchar(256)            not null comment 'Postion for the player of this game',
    competition_name  varchar(256) default '' not null
);

create table t_bowl_player
(
    id                          bigint auto_increment
        primary key,
    player_name                 varchar(256)  default 'Player' not null,
    player_email                varchar(256)  default ''       not null,
    player_gender               varchar(256)  default ''       not null,
    player_phone                varchar(256)  default ''       not null,
    player_availability         varchar(256)  default ''       not null comment 'plain text of available weekdays',
    player_pos_preference       varchar(256)  default ''       not null comment 'plain text of preferred position',
    player_prefer_teammates     varchar(256)  default ''       not null comment 'plain text of the names the player like to play with',
    player_not_prefer_teammates varchar(256)  default ''       not null comment 'plain text of the names the player do not like to play with',
    photo_url                   varchar(512)  default ''       null,
    recent_performance          double        default 0        not null comment 'Calculated by the recent five games'' performance of the player',
    notes                       varchar(1024) default 'empty'  not null
)
    comment 'record for player information';

INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5705, 'Ron Andersen', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5706, 'John Anderton', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5707, 'Janice Angus', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5708, 'Graham Baker', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5709, 'Eric Barrand', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5710, 'Adrian Barwell', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5711, 'Christine Battersby', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5712, 'Geoffrey Bausch', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5713, 'George Bell', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5714, 'Wendy Boce', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5715, 'Christine Bond', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5716, 'Janice (jan) Bourke', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5717, 'Lorraine Camm', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5718, 'Barrie Carson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5719, 'Paul Carstensen', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5720, 'Yvonne Carstensen', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5721, 'Nick Carter', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5722, 'Stephen Castle', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5723, 'John Chambers', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5724, 'Valerie Chaney', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5725, 'Margaret Chapman', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5726, 'Bonifacio Ciccarelli', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5727, 'Graeme Cobbett', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5728, 'Pauline Coe', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5729, 'Peter Coe', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5730, 'Geoffrey Collins', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5731, 'Kelvin Cooper', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5732, 'Fenton Coull', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5733, 'Michael (mick) Crawley', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5734, 'Reata Crawley', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5735, 'Barry Crittle', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5736, 'Bryan Cunningham', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5737, 'Adrian Dale', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5738, 'Janet Dawson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5739, 'Norman Dawson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5740, 'Christine Day', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5741, 'Jan Delaney', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5742, 'Peter Delaney', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5743, 'Marcello Di Martino', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5744, 'Norma Douglass', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5745, 'Sean Doyle', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5746, 'Trevor Ellis', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5747, 'Linda Fiander', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5748, 'Graeme Findlay', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5749, 'Roseann Firth', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5750, 'Julian Fitzgerald', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5751, 'Maureen Fitzgerald', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5752, 'Anne Fitzmaurice', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5753, 'Wolf Flanagan', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5754, 'Barry Fleming', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5755, 'Laurie Fraser', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5756, 'Max Fraser', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5757, 'Wayne Frazer', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5758, 'John Gillespie', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5759, 'Denis Gleeson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5760, 'Colin Goodrem', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5761, 'Joan Goodrem', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5762, 'Adrian Goldsmith', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5763, 'Graeme Griffiths', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5764, 'Robert Grosser', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5765, 'Louise Gunn', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5766, 'Bryan Hall', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5767, 'John Harding', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5768, 'Vicki Heath', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5769, 'Kevin Hibbert', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5770, 'Peter Holman', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5771, 'Kay Horley', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5772, 'Dickson Huang', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5773, 'Kevin Jago', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5774, 'Robert Jago', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5775, 'Dennis Jeffery', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5776, 'Joan Jeffery', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5777, 'Birthe Jensen', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5778, 'Kenneth Kelly', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5779, 'Lyn Kelly', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5780, 'Ravindra Khazanchi', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5781, 'Geoff King', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5782, 'Julie King', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5783, 'Judy Kingman', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5784, 'Gary Kitto', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5785, 'Milton Klingsporn', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5786, 'Donald Lambie', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5787, 'Keith Lampard', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5788, 'Victor (vic) Lampard', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5789, 'Graham Law', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5790, 'Morris Le Page', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5791, 'Miguel Magana', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5792, 'Terri Marley', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5793, 'Evelyn Martin', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5794, 'Albert Mason', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5795, 'Mario Mastromanno', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5796, 'Donald Matthews', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5797, 'Stewart McClure', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5798, 'Shane McCluskey', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5799, 'Barry Mc Craith', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5800, 'Donald (don) McDowell', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5801, 'Raymond McKean', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5802, 'Alison Meakin', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5803, 'Sid Meikle', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5804, 'Jack Meli', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5805, 'Sylvia Meli', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5806, 'Peter Miller', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5807, 'Roy Miller', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5808, 'Sue Miller', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5809, 'Brian Milnes', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5810, 'Jeanette Milnes', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5811, 'Kevin Moore', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5812, 'Patricia Moore', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5813, 'Janet Morrison', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5814, 'Phillip Morrison', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5815, 'Thomas Myors', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5816, 'Noreen O''Brien', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5817, 'Eileen O''Donnell', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5818, 'Bernard O''Sullivan', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5819, 'John Page', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5820, 'Chris Papettas', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5821, 'Sophia Papettas', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5822, 'John Parker', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5823, 'Shannon Parkin', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5824, 'Carole Parsons', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5825, 'Peter Parsons', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5826, 'Kenneth Pattison', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5827, 'Joy Paulsen', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5828, 'David Pearson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5829, 'Colin Perry', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5830, 'Ken Peverill', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5831, 'Patrick Phelan', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5832, 'John Pile', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5833, 'Laraine Pile', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5834, 'John Pilgrim', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5835, 'Ron Pinto', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5836, 'Ronald Portbury', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5837, 'Kevin Pryke', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5838, 'Dianne Quigley', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5839, 'Kevin Radford', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5840, 'Glenn Raymond', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5841, 'Alan Richards', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5842, 'Andrew Rintoul', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5843, 'Leon Ross', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5844, 'Justin Roy', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5845, 'Mirko Salinovic', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5846, 'Jim Saunders', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5847, 'Glenyce Schumer', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5848, 'John Sedgewick', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5849, 'Doiraine Sidbottom', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5850, 'Helma Simpson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5851, 'Molly Simpson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5852, 'Joy Smith', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5853, 'Lynette Snart', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5854, 'Stephen Staff', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5855, 'John Swale', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5856, 'Julienne Swale', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5857, 'Carol Swart', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5858, 'Lars Swart', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5859, 'Stephen Thek', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5860, 'Samuel Timmer', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5861, 'Valerie Turner', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5862, 'Miklos Tuz', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5863, 'Christopher Van de Loop', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5864, 'June Van de Ven', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5865, 'Klaus Werner', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5866, 'Marina Werner', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5867, 'David West', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5868, 'Janice (jan) Whitehead', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5869, 'Norman (norm) Whitehead', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5870, 'Albert (albie) Wiegard', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5871, 'Gil Williams', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5872, 'Robert (bob) Willis', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5873, 'Alan Wilson', '', '', '', '', '', '', '', '', 0, 'empty');
INSERT INTO BOWLS_CLUB.t_bowl_player (id, player_name, player_email, player_gender, player_phone, player_availability, player_pos_preference, player_prefer_teammates, player_not_prefer_teammates, photo_url, recent_performance, notes) VALUES (5874, 'Terrence Wright', '', '', '', '', '', '', '', '', 0, 'empty');

create table t_bowl_team
(
    id                  bigint auto_increment
        primary key,
    team_name           varchar(256) default 'New Team'      not null comment 'name of the team',
    skip_bowler_id1     bigint       default -1              not null comment 'player id of the skip bowler',
    skip_bowler_name1   varchar(256) default 'Skip bowler'   not null comment 'name of the skip player',
    third_bowler_id1    bigint       default -1              not null comment 'player id of the third_bowler',
    third_bowler_name1  varchar(256) default 'Third bowler'  not null comment 'name of the third_bowler',
    second_bowler_id1   bigint       default -1              not null comment 'player id of the second_bowler',
    second_bowler_name1 varchar(256) default 'Second bowler' not null comment 'name of the second_bowler',
    lead_bowler_id1     bigint       default -1              not null comment 'player id of the lead bowler',
    lead_bowler_name1   varchar(256) default 'Lead bowler'   not null comment 'name of the skip player',
    skip_bowler_id2     bigint       default -1              not null comment 'player id of the skip bowler',
    skip_bowler_name2   varchar(256) default 'Skip bowler'   not null comment 'name of the skip player',
    third_bowler_id2    bigint       default -1              not null comment 'player id of the third_bowler',
    third_bowler_name2  varchar(256) default 'Third bowler'  not null comment 'name of the third_bowler',
    second_bowler_id2   bigint       default -1              not null comment 'player id of the second_bowler',
    second_bowler_name2 varchar(256) default 'Second bowler' not null comment 'name of the second_bowler',
    lead_bowler_id2     bigint       default -1              not null comment 'player id of the lead bowler',
    lead_bowler_name2   varchar(256) default 'Lead bowler'   not null comment 'name of the skip player',
    skip_bowler_id3     bigint       default -1              not null comment 'player id of the skip bowler',
    skip_bowler_name3   varchar(256) default 'Skip bowler'   not null comment 'name of the skip player',
    third_bowler_id3    bigint       default -1              not null comment 'player id of the third_bowler',
    third_bowler_name3  varchar(256) default 'Third bowler'  not null comment 'name of the third_bowler',
    second_bowler_id3   bigint       default -1              not null comment 'player id of the second_bowler',
    second_bowler_name3 varchar(256) default 'Second bowler' not null comment 'name of the second_bowler',
    lead_bowler_id3     bigint       default -1              not null comment 'player id of the lead bowler',
    lead_bowler_name3   varchar(256) default 'Lead bowler'   not null comment 'name of the skip player',
    skip_bowler_id4     bigint       default -1              not null comment 'player id of the skip bowler',
    skip_bowler_name4   varchar(256) default 'Skip bowler'   not null comment 'name of the skip player',
    third_bowler_id4    bigint       default -1              not null comment 'player id of the third_bowler',
    third_bowler_name4  varchar(256) default 'Third bowler'  not null comment 'name of the third_bowler',
    second_bowler_id4   bigint       default -1              not null comment 'player id of the second_bowler',
    second_bowler_name4 varchar(256) default 'Second bowler' not null comment 'name of the second_bowler',
    lead_bowler_id4     bigint       default -1              not null comment 'player id of the lead bowler',
    lead_bowler_name4   varchar(256) default 'Lead bowler'   not null comment 'name of the skip player'
)
    comment 'record for the bowl teams';
    
    create table t_api_permission
(
    id   int auto_increment,
    uri  varchar(100) default '\\'       null,
    role varchar(50)  default 'selector' not null,
    constraint t_api_permission_id_uindex
        unique (id)
)
    comment 'Permission control';

alter table t_api_permission
    add primary key (id);

INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (1, '/sso/addUser', 'admin');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (2, '/sso/editUser', 'admin');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (3, '/sso/deleteUser', 'admin');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (4, '/competition/addCompetition', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (5, '/competition/deleteCompetitionById', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (6, '/competition/updateCompetition', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (7, '/player/addMatchPerformance', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (8, '/player/updateMatchPerformance', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (9, '/player/deleteMatchPerformanceById', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (10, '/player/getUserPerformances', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (11, '/player/getUserPerformancesByFilter', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (12, '/player/addPlayer', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (13, '/player/deletePlayerById', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (14, '/player/getAllPlayer', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (16, '/player/updatePlayer', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (17, '/team/addTeam', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (18, '/team/deleteTeam', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (20, '/team/updateTeam', 'selector');
INSERT INTO BOWLS_CLUB.t_api_permission (id, uri, role) VALUES (21, '/sso/getAllUser', 'admin');

create table t_user_info
(
    id                int auto_increment
        primary key,
    user_name         varchar(50)  default 'Nick Name'        not null,
    real_name         varchar(50)  default 'Real Name'        not null,
    email             varchar(100) default 'name@example.com' not null,
    password          varchar(50)  default '123456'           not null,
    role              varchar(50)  default 'selector'         not null,
    token             varchar(100) default 'token'            not null,
    token_create_date datetime                                null
)
    comment 'Selector and Admin Table';

INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (23, 'admin', 'admin', 'admin', 'admin', 'admin', '52a2ffadcf5343a8aeac206cf84de7c2', '2021-10-27 15:57:04');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (25, 'zijian', 'zijian Ju', 'zijianj', '123456', 'selector', '75ebe4c0c8794508a09a8e4063907d34', '2021-09-30 07:36:20');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (26, 'zhiyuan', 'zhiyuan', 'zhiyuan', 'zhiyuan', 'selector', '5547e026070b4c54885d52fa587b91a6', '2021-10-15 01:33:25');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (37, 'tiff', 'Tiff', 'tiff@gmail.com', '123456', 'selector', '6f6791036aaa44d686ccd3753e92e302', '2021-10-09 06:24:02');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (42, 'test@test.com', 'test', 'test@test.com', 'test', 'selector', 'bc4aa6078b97459f8d4c7bff7509296d', '2021-10-11 06:46:32');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (43, 'anu', 'Anu', 'anu@gmail.com', 'anu', 'selector', '4cf0631d7d174275999780bb1be6e6b5', '2021-10-26 02:51:20');
INSERT INTO BOWLS_CLUB.t_user_info (id, user_name, real_name, email, password, role, token, token_create_date) VALUES (44, 'selector', 'selector', 'selector', 'selector', 'selector', 'token', '2021-10-26 00:54:13');